---
- name: Update apt cache (package database) if needed
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  listen: apt update

- name: Reload AppArmor
  become: true
  ansible.builtin.systemd_service:
    name: apparmor.service
    state: reloaded
