---
- name: Update apt cache (package database) if needed
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  listen: apt update

- name: Reboot required
  become: true
  ansible.builtin.file:
    path: /var/run/reboot-required
    owner: root
    group: root
    mode: "0644"
    state: touch
