---
- name: Update apt cache (package database) if needed
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  listen: apt update

- name: Reload AppArmor
  become: true
  ansible.builtin.systemd_service:
    name: apparmor.service
    state: reloaded

- name: Write reboot-required file
  become: true
  ansible.builtin.copy:
    content: "*** System restart required ***\n"    # Typically this file is empty ¯\_(ツ)_/¯
    dest: /var/run/reboot-required
    owner: root
    group: root
    mode: "0644"
  listen: Reboot required

# TODO Variablize pkgs lines
#- name: Write reboot-required.pkgs file
#  become: true
#  ansible.builtin.lineinfile:
#    path: /var/run/reboot-required.pkgs
#    regexp: ^flatpak
#    line: "flatpak"
#    owner: root
#    group: root
#    mode: "0644"
#    create: true
#  listen: Reboot required
