---
- name: Install prerequisites
  become: true
  apt:
    name: libfuse2  # AppImage support
    state: present

- name: Make directory `Applications' if not exists
  file:
    path: "{{ users_custom_apps_dir }}"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    state: directory

- name: Download Cursor
  ansible.builtin.get_url:
    url: https://downloads.cursor.com/production/0781e811de386a0c5bcb07ceb259df8ff8246a52/linux/x64/Cursor-0.49.6-x86_64.AppImage
    dest: "{{ users_custom_apps_dir }}/Cursor.AppImage"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: a+x
    checksum: sha256:587e3f670d15266446c91ccc9644e19216787c6cac30a0544883c24ecc864b8c
    force: false    # Download every time to fail upon checksum change

- name: Make directory `.local/bin' if not exists
  file:
    path: "{{ users_local_bin_dir }}"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    state: directory

- name: Create symlink for CLI porpoise
  file:
    src: "{{ users_custom_apps_dir }}/Cursor.AppImage"
    dest: "{{ users_local_bin_dir }}/cursor"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    state: link

- name: Make directory `.local/share/icons/hicolor/1024x1024/apps' if not exists
  file:
    path: "{{ ansible_env.HOME }}/.local/share/icons/hicolor/1024x1024/apps"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    state: directory

- name: Copy application icon   # Taken from https://lobehub.com/icons/cursor
  copy:
    src: files/software/cursor/icon_1024x1024.png
    dest: "{{ ansible_env.HOME }}/.local/share/icons/hicolor/1024x1024/apps/cursor.png"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Create application's desktop entry
  copy:
    content: |
      [Desktop Entry]
      Name=Cursor
      Exec={{ users_local_bin_dir }}/cursor
      Icon={{ ansible_env.HOME }}/.local/share/icons/hicolor/1024x1024/apps/cursor.png
      Type=Application
      Categories=Development;
    dest: "{{ users_desktop_files_dir }}/cursor.desktop"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
    # TODO Validate does not comply to tempfile w/o .desktop extension
    # Though, works with
    # - ansible [core 2.18.4]
    # - desktop-file-validate 0.27
    validate: desktop-file-validate %s

# To uninstall, simply delete these following files:
# rm ~/.local/share/applications/cursor.desktop
# rm ~/.local/share/icons/hicolor/1024x1024/apps/cursor.png
# rm ~/.local/bin/cursor
# rm ~/Applications/Cursor.AppImage
