---
- name: Install Flatpak on Debian   # See also https://flathub.org/setup/Debian
  become: true
  when: ansible_os_family == 'Debian'
  notify: Reboot required
  block:
    - name: Install Flatpak
      ansible.builtin.apt:
        name: flatpak
        state: present

    - name: Install the GNOME Software Flatpak plugin
      when: lookup('env', 'XDG_CURRENT_DESKTOP') in ('GNOME', 'ubuntu:GNOME')
      ansible.builtin.apt:
        name: gnome-software-plugin-flatpak
        state: present

    # See https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/2061728/comments/5
    - name: Provide AppArmor profile to fix Flatpak handling from GNOME Software
      ansible.builtin.blockinfile:
        path: /etc/apparmor.d/bwrap
        block: |
          abi <abi/4.0>,
          include <tunables/global>

          profile bwrap /usr/bin/bwrap flags=(unconfined) {
            userns,

            # Site-specific additions and overrides. See local/README for details.
            include if exists <local/bwrap>
          }
        create: true
        owner: root
        group: root
        mode: "0644"
      notify: Reload AppArmor
      when: ansible_distribution == 'Ubuntu'

    - name: Install the Plasma Discover Flatpak backend
      when: lookup('env', 'XDG_CURRENT_DESKTOP') == 'KDE'
      ansible.builtin.apt:
        name: plasma-discover-backend-flatpak
        state: present

    # This replaces the Flatseal flatpak
    - name: Install the Plasma System Settings module
      when: lookup('env', 'XDG_CURRENT_DESKTOP') == 'KDE'
      ansible.builtin.apt:
        name: kde-config-flatpak
        state: present

    - name: Add the Flathub repository
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
        state: present
      ignore_errors: "{{ ansible_check_mode }}"   # flatpak executable not present

    - name: Install the Flatseal flatpak
      when: lookup('env', 'XDG_CURRENT_DESKTOP') in ('GNOME', 'ubuntu:GNOME')
      community.general.flatpak:
        name: com.github.tchx84.Flatseal
