---
- name: Import KDE Plasma related tasks
  import_tasks: kde.yaml
  when: ansible_facts.env['XDG_SESSION_DESKTOP'] == 'KDE'
  tags: kde

- name: Import Wayland related tasks
  import_tasks: wayland.yaml
  tags: wayland
