---
- name: Flatpak
  hosts: localhost
  connection: local

  tasks:
    - name: Install Flatpak on Debian   # See also https://flathub.org/setup/Debian
      become: true
      when: ansible_os_family == 'Debian'
      notify: Reboot required
      block:
        - name: Install Flatpak
          ansible.builtin.apt:
            name: flatpak
            state: present

        - name: Install the GNOME Software Flatpak plugin
          when: lookup('env', 'XDG_CURRENT_DESKTOP') == 'GNOME'
          ansible.builtin.apt:
            name: gnome-software-plugin-flatpak
            state: present

        - name: Install the Plasma Discover Flatpak backend
          when: lookup('env', 'XDG_CURRENT_DESKTOP') == 'KDE'
          ansible.builtin.apt:
            name: plasma-discover-backend-flatpak
            state: present

        - name: Add the Flathub repository
          community.general.flatpak_remote:
            name: flathub
            flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
            method: system
            state: present
          ignore_errors: "{{ ansible_check_mode }}"   # flatpak executable not present

  handlers:
    - name: Write reboot-required file
      become: true
      ansible.builtin.copy:
        content: "*** System restart required ***\n"    # Typically this file is empty ¯\_(ツ)_/¯
        dest: /var/run/reboot-required
        owner: root
        group: root
        mode: "0644"
      listen: Reboot required

    - name: Write reboot-required.pkgs file
      become: true
      ansible.builtin.lineinfile:
        path: /var/run/reboot-required.pkgs
        regexp: ^flatpak
        line: "flatpak"
        owner: root
        group: root
        mode: "0644"
        create: true
      listen: Reboot required
