---
- name: Managing Freifunk-Knoten
  hosts: freifunk
  gather_facts: false

  vars_prompt:
    - name: autoupdater_settings_enabled
      prompt: Enable (1) or disable (0) autoupdater?
      private: false

  tasks:
    - name: Gluon version
      block:
        - name: Peek Gluon version
          raw: cat /lib/gluon/gluon-version
          register: cat_result
          changed_when: false

        - name: Current Gluon version
          debug:
            msg: "{{ cat_result.stdout_lines[0] }}'"

    - name: Gluon release
      block:
        - name: Peek Gluon release
          raw: cat /lib/gluon/release
          register: cat_result
          changed_when: false

        - name: Current Gluon release
          debug:
            msg: "{{ cat_result.stdout_lines[0] }}'"

    - name: autoupdater status
      tags: autoupdater
      block:
        - name: Peek autoupdater status
          raw: uci get autoupdater.settings.enabled
          register: uci_result
          changed_when: false

        - name: Current autoupdater status
          debug:
            msg: "autoupdater.settings.enabled='{{ uci_result.stdout_lines[0] }}'"

        - name: "Set prompted autoupdater status to {{ autoupdater_settings_enabled }}"
          raw: "uci set autoupdater.settings.enabled={{ autoupdater_settings_enabled }} && uci commit autoupdater"

    - name: Handle lights
      tags: lights
      block:
        - name: Turn off lights
          raw: echo 0 >/sys/class/leds/blue:dome/brightness
