---
- name: Install 3rd party software
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - role: common
      tags: common

  tasks:
    - name: Import Signal related installation tasks
      ansible.builtin.import_tasks: tasks/signal.yaml
      tags: signal
