---
- name: Install 3rd party software
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - role: common
      tags: common

  tasks:
    - name: Import Brave related installation tasks
      ansible.builtin.import_tasks: tasks/brave.yml
      tags: brave

    - name: Import Flatpak related installation tasks
      ansible.builtin.import_tasks: tasks/flatpak.yaml
      tags: flatpak

    - name: Import Signal related installation tasks
      ansible.builtin.import_tasks: tasks/signal.yaml
      tags: signal

    - name: Import snap related installation tasks
      ansible.builtin.import_tasks: tasks/snapcraft.yml
      tags: snapcraft

    - name: Import VSCodium related installation tasks
      ansible.builtin.import_tasks: tasks/vscodium.yaml
      tags: vscodium
